import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-century-gothic">
        <Header />
        <main className="max-w-[100vw] px-generic pageTopBottonMargin overflow-hidden">
          <hr className="w-48 h-0.5 mb-1.5 bg-gray-200" />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
