import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import QueryProviders from '@/ReatQuery/provider';

export const metadata: Metadata = {
  title: "Blockchain Briefing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-montserrat">
        <QueryProviders>
          <Header />
          <main className="flex items-center justify-center md:px-generic pageTopBottonMargin overflow-hidden">
            <div className="max-width">
              <div className="max-md:flex max-md:justify-center max-md:items-center">
                <hr className="w-64 h-0.5 mb-2 bg-gray-200" />
              </div>
              {children}
            </div>
          </main>
          <Footer />
        </QueryProviders>
      </body>
    </html>
  );
}
